version: "3.7"
services:

  gtfs2cratedb:
    build: .
    image: gtfs2cratedb:0.0.1
    env_file: .env
    environment:
      - CRATE_DB_HOST=crate-db:4200
    ports:
      - "5000:5000"

  crate-db:
    image: "crate"
    ports:
      - "4200:4200"
